{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "litlyx.secretName" . }}
  labels:
    {{- include "litlyx.labels" . | nindent 4 }}
  {{- with .Values.secrets.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.redis.enabled }}
  redis-password: {{ .Values.redis.auth.password | b64enc }}
  {{- else if .Values.externalRedis.enabled }}
  redis-password: {{ .Values.externalRedis.password | b64enc }}
  {{- end }}

  {{- if .Values.mongodb.enabled }}
  mongodb-password: {{ .Values.mongodb.auth.rootPassword | b64enc }}
  {{- else if .Values.externalMongodb.enabled }}
  mongodb-password: {{ .Values.externalMongodb.password | b64enc }}
  {{- end }}

  jwt-secret: {{ .Values.dashboard.auth.jwtSecret | b64enc }}
  noauth-user-password: {{ .Values.dashboard.auth.noAuthUser.password | b64enc }}

  {{- if eq .Values.dashboard.auth.mode "GOOGLE" }}
  google-client-id: {{ .Values.dashboard.auth.google.clientId | b64enc }}
  google-client-secret: {{ .Values.dashboard.auth.google.clientSecret | b64enc }}
  {{- end }}

  {{- if .Values.dashboard.ai.enabled }}
  openai-organization: {{ .Values.dashboard.ai.openai.organization | b64enc }}
  openai-project: {{ .Values.dashboard.ai.openai.project | b64enc }}
  openai-api-key: {{ .Values.dashboard.ai.openai.apiKey | b64enc }}
  {{- end }}

  {{- if or .Values.dashboard.email.enabled .Values.consumer.email.enabled }}
  brevo-api-key: {{ .Values.dashboard.email.brevoApiKey | default .Values.consumer.email.brevoApiKey | b64enc }}
  {{- end }}

  {{- if .Values.dashboard.stripe.enabled }}
  stripe-secret-key: {{ .Values.dashboard.stripe.secretKey | b64enc }}
  stripe-webhook-secret: {{ .Values.dashboard.stripe.webhookSecret | b64enc }}
  {{- if .Values.dashboard.stripe.testMode }}
  stripe-test-secret-key: {{ .Values.dashboard.stripe.testSecretKey | b64enc }}
  stripe-test-webhook-secret: {{ .Values.dashboard.stripe.testWebhookSecret | b64enc }}
  {{- end }}
  {{- end }}

  {{- range $key, $value := .Values.secrets.data }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}
